"use client";
import { useMemo,useState } from "react";
import { casesSeed,statusLabels,type CaseItem } from "../demo-data";
export default function AdminPage(){
 const [selected,setSelected]=useState<CaseItem|null>(null); const [query,setQuery]=useState("");
 const rows=useMemo(()=>casesSeed.filter(c=>`${c.id} ${c.holder} ${c.location}`.toLowerCase().includes(query.toLowerCase())),[query]);
 return <main className="admin-app"><aside className="admin-sidebar"><div className="admin-logo"><span>▣</span><div><b>KÖNA</b><small>Koffer Übergabe</small></div></div><nav>{["Dashboard","Koffer","Übergaben","Karte","Inhaltsübersicht","Hinweise","Berichte","Einstellungen"].map((x,i)=><button className={i===0?"active":""} key={x}><span>{["⌂","▣","⇄","⌖","▤","!","▥","⚙"][i]}</span>{x}</button>)}</nav><div className="refresh"><small>Letzte Aktualisierung</small><b>vor 2 Minuten</b></div><div className="admin-user"><b>JL</b><div>Jakub Leitner<small>Administrator</small></div><span>⌄</span></div></aside>
 <section className="admin-content"><header className="dashboard-header"><div><h1>Dashboard</h1><p>Übersicht aller Koffer und Übergaben</p></div><div className="header-tools"><button>▣ 01.07.2025 – 13.07.2025⌄</button><button className="bell">♢<i>3</i></button></div></header>
 <section className="metric-grid"><Metric icon="▣" label="Gesamt Koffer" value="30" text="Alle Koffer im System" tone="teal"/><Metric icon="✓" label="Aktuell vergeben" value="22" text="In Nutzung" tone="green"/><Metric icon="◷" label="Wartet auf Übernahme" value="4" text="Bereit zur Abholung" tone="orange"/><Metric icon="▣" label="Verfügbar" value="4" text="Frei und bereit" tone="gray"/><Metric icon="!" label="Hinweise" value="3" text="Abweichungen / Fehler" tone="red"/></section>
 <section className="dashboard-panels"><div className="panel map-panel"><PanelTitle title="Koffer auf der Karte"/><div className="real-map"><span className="road r1"/><span className="road r2"/><span className="road r3"/><label className="place p-f">Freistadt</label><label className="place p-r">Rainbach</label><label className="place p-s">Sandl</label><label className="place p-g">Grünbach</label><button className="cluster green m1">5</button><button className="cluster orange m2">2</button><button className="cluster red m3">1</button><button className="map-control">＋<br/>−<br/>◎</button><button className="map-open">Karte öffnen ↗</button></div></div>
 <div className="panel"><PanelTitle title="Letzte Übergaben" action="Alle anzeigen"/>{[["KFR-012","Jakub Leitner → Max Mustermann","13.07.2025","14:32","green"],["KFR-007","Lisa Wagner → Thomas Berger","13.07.2025","11:08","green"],["KFR-021","Wartet auf Übernahme","13.07.2025","09:15","orange"],["KFR-003","Maria Huber → Peter Neumann","12.07.2025","18:42","green"],["KFR-018","Stefan Bauer → Lisa Wagner","12.07.2025","16:21","green"]].map(x=><div className="activity" key={x[0]}><i className={x[4]}/><span><b>{x[0]}</b><small>{x[1]}</small></span><time>{x[2]}<small>{x[3]}</small></time></div>)}<button className="panel-footer">Alle Übergaben anzeigen ›</button></div>
 <div className="panel"><PanelTitle title="Hinweise" action="Alle anzeigen"/>{[["KFR-007","2 Gegenstände fehlen","13.07.2025","red"],["KFR-015","1 Gegenstand beschädigt","12.07.2025","orange"],["KFR-003","Abweichung bei 1 Gegenstand","12.07.2025","orange"]].map(x=><button className="notice-row" key={x[0]}><i className={x[3]}/><span><b>{x[0]}</b><small>{x[1]}</small></span><time>{x[2]}</time></button>)}<button className="panel-footer">Alle Hinweise anzeigen ›</button></div></section>
 <section className="panel all-cases"><div className="table-header"><h2>Alle Koffer</h2><div><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Koffer suchen..."/></label><button>⚗ Filter</button><button>⇩ Export</button></div></div><div className="table-scroll"><table><thead><tr><th>Koffer ID</th><th>Status</th><th>Aktueller Besitzer</th><th>Standort</th><th>Letzte Übergabe</th><th>Hinweise</th><th/></tr></thead><tbody>{rows.map(c=><tr key={c.id} onClick={()=>setSelected(c)}><td><b>{c.id}</b></td><td><span className={`status-pill ${c.status}`}>{statusLabels[c.status]}</span></td><td>{c.holder}</td><td>⌖ {c.location}</td><td>{c.updated}</td><td>{c.inventory.some(x=>x.actual!==x.expected)?<span className="issue-count">● 1</span>:"–"}</td><td>›</td></tr>)}</tbody></table></div></section>
 </section>
 {selected&&<div className="drawer-overlay" onClick={()=>setSelected(null)}><aside className="case-drawer" onClick={e=>e.stopPropagation()}><button className="drawer-close" onClick={()=>setSelected(null)}>×</button><p>{selected.id}</p><h2>{selected.name}</h2><span className={`status-pill ${selected.status}`}>{statusLabels[selected.status]}</span><div className="drawer-info"><small>Aktueller Besitzer</small><b>{selected.holder}</b><small>Standort</small><b>{selected.address}</b><small>Letzte Übergabe</small><b>{selected.updated}</b></div><h3>Kofferinhalt</h3>{selected.inventory.map(x=><div className="drawer-item" key={x.name}><span>{x.icon} {x.name}</span><b className={x.actual!==x.expected?"danger":""}>{x.actual} / {x.expected}</b></div>)}<h3>Verlauf</h3>{selected.history.map(h=><div className="history-item" key={h.date}><b>{h.title}</b><small>{h.date} · {h.detail}</small></div>)}<a className="open-case" href={`/koffer/${selected.id}`}>Öffentliche Kofferseite öffnen ↗</a></aside></div>}
 </main>;
}
function Metric({icon,label,value,text,tone}:{icon:string;label:string;value:string;text:string;tone:string}){return <div className="metric"><span className={tone}>{icon}</span><div><small>{label}</small><b>{value}</b><p>{text}</p></div></div>}
function PanelTitle({title,action}:{title:string;action?:string}){return <div className="panel-title"><h2>{title}</h2>{action&&<button>{action}</button>}</div>}
