"use client";
import { useMemo, useState } from "react";
import { QRCodeSVG } from "qrcode.react";

type Status="frei"|"unterwegs"|"reserviert"|"offen"|"abweichung";
type Inventory={name:string;expected:number;actual:number};
type CaseItem={id:string;name:string;status:Status;holder:string;address:string;updated:string;next?:string;inventory:Inventory[];history:{date:string;title:string;detail:string}[]};
type View="dashboard"|"bookings"|"handover";

const seed:CaseItem[]=[
{id:"K-001",name:"Einsatzkoffer Nord",status:"frei",holder:"Lager Freistadt",address:"Industriestraße 2, 4240 Freistadt",updated:"Heute, 09:10",next:"20.–24. Juli",inventory:[{name:"Server",expected:1,actual:1},{name:"Drucker",expected:2,actual:2},{name:"Handys",expected:5,actual:5},{name:"USV",expected:1,actual:1},{name:"Tablets",expected:3,actual:3},{name:"Router",expected:2,actual:2},{name:"Kabelsets",expected:4,actual:4}],history:[{date:"14.07.2026",title:"Rückgabe abgeschlossen",detail:"Lager Freistadt"}]},
{id:"K-002",name:"Einsatzkoffer Süd",status:"unterwegs",holder:"Max Huber",address:"Hauptstraße 14, 4020 Linz",updated:"Heute, 14:32",next:"Rückgabe 17. Juli",inventory:[{name:"Server",expected:1,actual:1},{name:"Drucker",expected:2,actual:2},{name:"Handys",expected:5,actual:5},{name:"USV",expected:1,actual:1},{name:"Tablets",expected:3,actual:3},{name:"Router",expected:2,actual:2},{name:"Kabelsets",expected:4,actual:4}],history:[{date:"12.07.2026",title:"Übernommen",detail:"Max Huber · Linz"},{date:"01.07.2026",title:"Rückgabe",detail:"Lager Freistadt"}]},
{id:"K-003",name:"Einsatzkoffer West",status:"offen",holder:"Peter Gruber",address:"Ringstraße 8, 4600 Wels",updated:"Gestern, 18:10",next:"Übernahme offen",inventory:[{name:"Server",expected:1,actual:1},{name:"Drucker",expected:2,actual:2},{name:"Handys",expected:5,actual:5},{name:"USV",expected:1,actual:1},{name:"Tablets",expected:3,actual:3},{name:"Router",expected:2,actual:2},{name:"Kabelsets",expected:4,actual:4}],history:[{date:"13.07.2026",title:"Abschluss durch Vormieter",detail:"Peter Gruber · Wels"}]},
{id:"K-004",name:"Einsatzkoffer Ost",status:"reserviert",holder:"Lager Freistadt",address:"Industriestraße 2, 4240 Freistadt",updated:"12.07.2026",next:"15.–19. Juli",inventory:[{name:"Server",expected:1,actual:1},{name:"Drucker",expected:2,actual:2},{name:"Handys",expected:5,actual:5},{name:"USV",expected:1,actual:1},{name:"Tablets",expected:3,actual:3},{name:"Router",expected:2,actual:2},{name:"Kabelsets",expected:4,actual:4}],history:[{date:"10.07.2026",title:"Reserviert",detail:"Einsatz Wien"}]},
{id:"K-005",name:"Einsatzkoffer Mitte",status:"abweichung",holder:"Anna Maier",address:"Neubaugasse 20, 1070 Wien",updated:"11.07.2026",next:"Rückgabe 16. Juli",inventory:[{name:"Server",expected:1,actual:1},{name:"Drucker",expected:2,actual:1},{name:"Handys",expected:5,actual:5},{name:"USV",expected:1,actual:1},{name:"Tablets",expected:3,actual:3},{name:"Router",expected:2,actual:2},{name:"Kabelsets",expected:4,actual:3}],history:[{date:"11.07.2026",title:"Übernahme mit Abweichung",detail:"1 Drucker und 1 Kabelset fehlen"}]}
];
const labels:Record<Status,string>={frei:"Verfügbar",unterwegs:"Unterwegs",reserviert:"Reserviert",offen:"Übernahme offen",abweichung:"Abweichung"};

export default function Home(){
 const [cases,setCases]=useState(seed); const [view,setView]=useState<View>("dashboard"); const [selected,setSelected]=useState("K-002"); const [modal,setModal]=useState(false); const [notice,setNotice]=useState("");
 const current=cases.find(c=>c.id===selected)??cases[0];
 const totals=useMemo(()=>({free:cases.filter(c=>c.status==="frei").length+7,out:cases.filter(c=>c.status==="unterwegs"||c.status==="abweichung").length+15,booked:cases.filter(c=>c.status==="reserviert").length+2,open:cases.filter(c=>c.status==="offen").length+1}),[cases]);
 const book=(id:string)=>{setCases(x=>x.map(c=>c.id===id?{...c,status:"reserviert",next:"20.–24. Juli"}:c));setNotice(`${id} wurde für 20.–24. Juli reserviert.`)};
 return <div className="app">{view==="handover"?<Handover cases={cases} setCases={setCases} onAdmin={()=>setView("dashboard")}/>:<>
 <aside className="sidebar"><div className="logo"><span>KÖ</span><div>KÖNA<small>Kofferverwaltung</small></div></div><nav><button className={view==="dashboard"?"active":""} onClick={()=>setView("dashboard")}>▦ <span>Übersicht</span></button><button className={view==="bookings"?"active":""} onClick={()=>setView("bookings")}>▣ <span>Buchungen</span></button><button onClick={()=>setView("handover")}>▧ <span>Übergabe testen</span></button></nav><div className="admin"><b>JL</b><div>Jakub Leitner<small>Administrator</small></div></div></aside>
 <main className="admin-main"><header className="admin-header"><div><p className="eyebrow">Dienstag, 14. Juli 2026</p><h1>{view==="bookings"?"Buchungen":"Kofferübersicht"}</h1><p>{view==="bookings"?"Verfügbarkeiten prüfen und Zeiträume reservieren.":"Standorte, Übergaben und Abweichungen im Blick."}</p></div><button className="btn primary" onClick={()=>setView("handover")}>QR-Übergabe öffnen</button></header>{notice&&<div className="notice">✓ {notice}<button onClick={()=>setNotice("")}>×</button></div>}
 {view==="dashboard"?<><section className="stats"><Stat n={totals.free} t="verfügbar"/><Stat n={totals.out} t="unterwegs"/><Stat n={totals.booked} t="reserviert"/><Stat n={totals.open} t="offene Übergaben"/></section><section className="dashboard-grid"><div className="card map-card"><CardHead title="Aktuelle Standorte" sub="Letzter bestätigter Standort"/><div className="map"><i/><i/><i/><button className="pin p1" onClick={()=>{setSelected("K-001");setModal(true)}}>1</button><button className="pin p2" onClick={()=>{setSelected("K-002");setModal(true)}}>2</button><button className="pin p3 warn" onClick={()=>{setSelected("K-005");setModal(true)}}>5</button><span className="city c1">FREISTADT</span><span className="city c2">LINZ</span><span className="city c3">WIEN</span></div></div><div className="card attention"><CardHead title="Heute beachten" sub="3 Vorgänge brauchen Aufmerksamkeit"/><Task tone="orange" title="K-003 wartet auf Übernahme" text="Abschluss durch Peter Gruber · Wels" onClick={()=>setView("handover")}/><Task tone="red" title="K-005: Fehlbestand" text="1 Drucker und 1 Kabelset fehlen" onClick={()=>{setSelected("K-005");setModal(true)}}/><Task tone="blue" title="K-002 Rückgabe in 3 Tagen" text="Max Huber · Linz" onClick={()=>{setSelected("K-002");setModal(true)}}/></div></section><section className="card case-table"><CardHead title="Alle Koffer" sub="30 Koffer im produktiven Bestand"/><div className="table-wrap"><table><thead><tr><th>Koffer</th><th>Status</th><th>Aktuell bei</th><th>Standort</th><th>Nächster Termin</th></tr></thead><tbody>{cases.map(c=><tr key={c.id} onClick={()=>{setSelected(c.id);setModal(true)}}><td><b>{c.id}</b><small>{c.name}</small></td><td><Status status={c.status}/></td><td>{c.holder}</td><td>{c.address.split(",").slice(-1)}</td><td>{c.next||"–"}</td></tr>)}</tbody></table></div></section></>:<Bookings cases={cases} onBook={book}/>}</main>{modal&&<Drawer item={current} onClose={()=>setModal(false)} onHandover={()=>{setModal(false);setView("handover")}}/>}</>}</div>
}
function Stat({n,t}:{n:number;t:string}){return <div className="stat"><strong>{n}</strong><span>{t}</span></div>}
function CardHead({title,sub}:{title:string;sub:string}){return <div className="card-head"><div><h2>{title}</h2><p>{sub}</p></div><button>Mehr →</button></div>}
function Status({status}:{status:Status}){return <span className={`status ${status}`}>{labels[status]}</span>}
function Task({tone,title,text,onClick}:{tone:string;title:string;text:string;onClick:()=>void}){return <button className="task" onClick={onClick}><b className={tone}>!</b><span><strong>{title}</strong><small>{text}</small></span><i>→</i></button>}
function Bookings({cases,onBook}:{cases:CaseItem[];onBook:(id:string)=>void}){const free=cases.filter(c=>c.status==="frei");return <><section className="booking-hero"><p className="eyebrow">Zeitraum auswählen</p><h2>Welcher Koffer ist frei?</h2><div className="booking-fields"><label>Von<input type="date" defaultValue="2026-07-20"/></label><label>Bis<input type="date" defaultValue="2026-07-24"/></label><label>Einsatzort<input placeholder="z. B. Linz"/></label><button className="btn primary">Verfügbarkeit prüfen</button></div></section><section className="card booking-list"><CardHead title="Verfügbare Koffer" sub="20.–24. Juli 2026"/>{free.map(c=><div className="booking-row" key={c.id}><div><b>{c.id}</b><small>{c.name} · {c.address}</small></div><Status status="frei"/><button className="btn primary small" onClick={()=>onBook(c.id)}>Buchen</button></div>)}</section></>}
function Drawer({item,onClose,onHandover}:{item:CaseItem;onClose:()=>void;onHandover:()=>void}){return <div className="overlay" onClick={onClose}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose}>×</button><p className="eyebrow">Kofferakte</p><h2>{item.id}</h2><p className="muted">{item.name}</p><Status status={item.status}/><div className="detail"><label>Aktuell bei<strong>{item.holder}</strong></label><label>Standort<strong>{item.address}</strong></label><label>Zuletzt aktualisiert<strong>{item.updated}</strong></label></div><h3>Kofferinhalt</h3><div className="inventory">{item.inventory.map(x=><div key={x.name}><span>{x.name}</span><b className={x.actual!==x.expected?"bad":""}>{x.actual} / {x.expected}</b></div>)}</div><h3>Verlauf</h3><div className="timeline">{item.history.map((h,i)=><div key={i}><b>{h.title}</b><small>{h.date}<br/>{h.detail}</small></div>)}</div><button className="btn primary wide" onClick={onHandover}>Übergabe öffnen</button></aside></div>}

function Handover({cases,setCases,onAdmin}:{cases:CaseItem[];setCases:React.Dispatch<React.SetStateAction<CaseItem[]>>;onAdmin:()=>void}){
 const [step,setStep]=useState(1); const [caseId,setCaseId]=useState("K-003"); const [name,setName]=useState(""); const [address,setAddress]=useState(""); const [mode,setMode]=useState<"takeover"|"return">("takeover"); const [items,setItems]=useState<Inventory[]>(cases.find(c=>c.id==="K-003")!.inventory.map(x=>({...x}))); const [note,setNote]=useState("");
 const found=cases.find(c=>c.id===caseId); const issue=items.some(x=>x.actual!==x.expected);
 const scan=()=>{setCaseId("K-003");const c=cases.find(x=>x.id==="K-003");if(c)setItems(c.inventory.map(x=>({...x})));};
 const next=()=>{if(step===1&&!found)return;setStep(s=>Math.min(4,s+1))};
 const finish=()=>{setCases(all=>all.map(c=>c.id!==caseId?c:{...c,status:issue?"abweichung":mode==="return"?"frei":"unterwegs",holder:mode==="return"?"Lager Freistadt":name||"Neuer Übernehmer",address:mode==="return"?"Industriestraße 2, 4240 Freistadt":address||c.address,updated:"Gerade eben",inventory:items,history:[{date:"14.07.2026",title:mode==="return"?"Rückgabe abgeschlossen":"Übernahme bestätigt",detail:`${name||"Unbekannt"}${note?` · ${note}`:""}`},...c.history]}));setStep(4)};
 return <div className="mobile-bg"><section className="phone"><header className="mobile-head"><div className="logo"><span>KÖ</span><div>KÖNA<small>Übergabe</small></div></div><button onClick={onAdmin}>Admin</button></header><div className="mobile-content">{step<4&&<div className="progress">{[1,2,3].map(n=><i key={n} className={step>=n?"active":""}/>)}</div>}
 {step===1&&<><p className="eyebrow">Schritt 1 von 3</p><h1>Koffer scannen</h1><p className="lead">Scanne den QR-Code am Koffer oder gib die Koffer-ID ein.</p><div className="scan-card"><div className="scan-frame"><QRCodeSVG value={`https://koena.example/case/${caseId}`} size={120}/></div><button className="btn accent wide" onClick={scan}>▦ QR-Code scannen</button></div><label className="field">Koffer-ID<input value={caseId} onChange={e=>setCaseId(e.target.value.toUpperCase())} placeholder="z. B. K-001"/></label>{caseId&&!found&&<p className="error">Dieser Koffer wurde nicht gefunden.</p>}</>}
 {step===2&&<><p className="eyebrow">Schritt 2 von 3</p><h1>{found?.status==="offen"?"Wer übernimmt?":"Koffer übergeben"}</h1><p className="lead">Name und aktuellen Standort eintragen.</p><label className="field">Vollständiger Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Vor- und Nachname"/></label><label className="field">Adresse / Standort<textarea value={address} onChange={e=>setAddress(e.target.value)} rows={4} placeholder="Straße, Hausnummer, PLZ, Ort"/></label><div className="mode-card"><strong>Vorgang</strong><div><button className={mode==="takeover"?"selected":""} onClick={()=>setMode("takeover")}>Übernahme</button><button className={mode==="return"?"selected":""} onClick={()=>setMode("return")}>Rückgabe</button></div></div></>}
 {step===3&&<><p className="eyebrow">Schritt 3 von 3</p><h1>Alles überprüfen</h1><p className="lead">Kofferinhalt zählen. Die Mengen können direkt verändert werden.</p><div className="summary"><div><span>Koffer</span><b>{caseId}</b><button onClick={()=>setStep(1)}>Ändern</button></div><div><span>{mode==="return"?"Rückgabe durch":"Übernahme durch"}</span><b>{name||"Noch nicht angegeben"}</b><button onClick={()=>setStep(2)}>Ändern</button></div><div><span>Standort</span><b>{address||found?.address}</b></div></div><div className="section-title"><h2>Kofferinhalt</h2><Status status={issue?"abweichung":"frei"}/></div><div className="count-list">{items.map((x,i)=><div key={x.name}><span><b>{x.name}</b><small>Soll: {x.expected}</small></span><button onClick={()=>setItems(a=>a.map((v,j)=>j===i?{...v,actual:Math.max(0,v.actual-1)}:v))}>−</button><strong>{x.actual}</strong><button onClick={()=>setItems(a=>a.map((v,j)=>j===i?{...v,actual:v.actual+1}:v))}>+</button></div>)}</div>{issue&&<div className="warning">Abweichungen werden dokumentiert und im Dashboard markiert.</div>}<label className="field">Notiz (optional)<textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Fehlende oder beschädigte Teile beschreiben"/></label></>}
 {step===4&&<div className="success"><div>✓</div><p className="eyebrow">Erfolgreich abgeschlossen</p><h1>{mode==="return"?"Rückgabe":"Übernahme"} bestätigt</h1><p>Standort und Kofferinhalt wurden gespeichert.</p><button className="btn primary wide" onClick={()=>{setStep(1);setName("");setAddress("");setNote("")}}>Neue Übergabe</button><button className="btn text wide" onClick={onAdmin}>Zum Dashboard</button></div>}</div>{step<4&&<footer className="mobile-actions">{step>1&&<button className="btn secondary" onClick={()=>setStep(s=>s-1)}>Zurück</button>}<button className="btn primary" onClick={step===3?finish:next} disabled={step===1&&!found}>{step===3?"Vorgang abschließen":"Weiter"}</button></footer>}</section></div>
}
